export const SSC_DEGREE_OPTIONS = [
  'SSC',
  'O-Level',
  'Dakhil (Madrasah)',
  'SSC (Vocational)',
] as const;

export type TSSC_DegreeOption = (typeof SSC_DEGREE_OPTIONS)[number];

export const HSC_DEGREE_OPTIONS = [
  'HSC',
  'A-Level',
  'Alim (Madrasah)',
  'HSC (Vocational)',
  'HSC (BMT)',
] as const;

export type THSC_DegreeOption = (typeof HSC_DEGREE_OPTIONS)[number];

export const DIPLOMA_DEGREE_OPTIONS = [
  'Certificate in Marine Trade',
  'Diploma (Vocational)',
  'Diploma in Agriculture',
  'Diploma in Anesthesiology (DA)',
  'Diploma in Architecture',
  'Diploma in Automobile',
  'Diploma in Biomedical Engineering (BME)',
  'Diploma in Business Studies',
  'Diploma in Cardiology (D.Card)',
  'Diploma in Civil',
  'Diploma in Commerce',
  'Diploma in Computer',
  'Diploma in Culinary Art',
  'Diploma in Electrical',
  'Diploma in Electro Medical Engineering (EME)',
  'Diploma in Electro medical',
  'Diploma in Electronics',
  'Diploma in Engineering',
  'Diploma in Fisheries',
  'Diploma in Forestry',
  'Diploma in Glass & Ceramic Technology',
  'Diploma in Gynecology and Obstetrics (DGO)',
  'Diploma in Health Technology and Services',
  'Diploma in Hotel Management',
  'Diploma in Laryngology and Otology (DLO)',
  'Diploma in Livestock',
  'Diploma in Marine Engineering',
  'Diploma in Mechanical',
  'Diploma in Medical',
  'Diploma in Medical Technology',
  'Diploma in Medical Technology (Physiotherapy)',
  'Diploma in Medical Ultrasound',
  'Diploma in Midwifery',
  'Diploma in Nursing',
  'Diploma in Orthopaedics (D.Ortho)',
  'Diploma in Pathology',
  'Diploma in Power',
  'Diploma in Refrigeration and Air Conditioning',
  'Diploma in Textile Engineering',
  'Membership of the Royal College of Obstetricians and Gynaecologists (MRCOG)',
  'Membership of the Royal Colleges of Physicians (MRCP)',
  'Membership of the Royal Colleges of Surgeons (MRCS)',
  'Post Graduate Diploma (PGD)',
] as const;

export type TDiplomaDegreeOption = (typeof DIPLOMA_DEGREE_OPTIONS)[number];

export const BACHELOR_DEGREE_OPTIONS = [
  'Bachelor in Engineering (BEngg)',
  'Bachelor of Architecture (B.Arch)',
  'Bachelor of Arts (BA)',
  'Bachelor of Arts (Pass)',
  'Bachelor of Business Administration (BBA)',
  'Bachelor of Business Studies (BBS)',
  'Bachelor of Business Studies (Pass)',
  'Bachelor of Commerce (BCom)',
  'Bachelor of Commerce (Pass)',
  'Bachelor of Computer Application (BCA)',
  'Bachelor of Dental Surgery (BDS)',
  'Bachelor of Education (B.Ed)',
  'Bachelor of Fine Arts (B.F.A)',
  'Bachelor of Law (LLB)',
  'Bachelor of Law (Pass)',
  'Bachelor of Medicine and Bachelor of Surgery (MBBS)',
  'Bachelor of Pharmacy (B.Pharm)',
  'Bachelor of Physical Education (BPEd)',
  'Bachelor of Physiotherapy (BPT)',
  'Bachelor of Public Health',
  'Bachelor of Real Estate (BRE)',
  'Bachelor of Science (BSc)',
  'Bachelor of Science (Pass)',
  'Bachelor of Social Science (BSS)',
  'Bachelor of Social Science (Pass)',
  'Doctor of Veterinary Medicine (DVM)',
  'Fazil (Madrasah Hons.)',
  'Fazil (Madrasah Pass)',
] as const;

export type TBachelorDegreeOption = (typeof BACHELOR_DEGREE_OPTIONS)[number];

export const POSTGRADUATE_DEGREE_OPTIONS = [
  'Doctor of Medicine (MD)',
  'Executive Master of Business Administration (EMBA)',
  'Fellowship of the College of Physicians and Surgeons (FCPS)',
  'Kamil (Madrasah)',
  'Master of Architecture (M.Arch)',
  'Master of Arts (MA)',
  'Master of Business Administration (MBA)',
  'Master of Business Management (MBM)',
  'Master of Business Studies (MBS)',
  'Master of Commerce (MCom)',
  'Master of Development Studies (MDS)',
  'Master of Disability Management and Rehabilitation (MDMR)',
  'Master of Education (M.Ed)',
  'Master of Fine Arts (M.F.A)',
  'Master of Information & Communication Technology (MICT)',
  'Master of Law (LLM)',
  'Master of Pharmacy (M.Pharm)',
  'Master of Philosophy (M.Phil)',
  'Master of Physiotherapy (MPT)',
  'Master of Professional Banking (MPB)',
  'Master of Professional Finance (MPF)',
  'Master of Professional Marketing (MPM)',
  'Master of Professional MIS (MPMIS)',
  'Master of Science (MSc)',
  'Master of Social Science (MSS)',
  'Master of Surgery (MS)',
  'Masters in Bank Management (MBM)',
  'Masters in Computer Application (MCA)',
  'Masters in Engineering (MEngg)',
  'Masters in Information Systems Security (MISS)',
  'Masters of Professional Human Resource Management (MPHRM)',
  'Others',
] as const;

export type TPostgraduateDegreeOption =
  (typeof POSTGRADUATE_DEGREE_OPTIONS)[number];
